data_dir: /nfs/diskstation/projects/registration/data/training_data
output_file: /nfs/diskstation/projects/registration/data/conv_models/salient_edge_net.h5
validation_pct: 0.2
model_cfg:
    n_filters: 32
    kernel_size: 7
    input_width: 256
    input_height: 256
    input_channels: 4
training_cfg:
    learning_rate: 0.01
    num_epochs: 100
    cuda_device: 2
